### PR TITLE
Standardise 'related-area-of-need' in edit-goal controller

### PR DESCRIPTION
**Pull request by Thomas-Geraghty**
- Whilst creating the edit-goal controller, I somehow switched from 'related-area-of-need' to 'other-area-of-need'
- This PR just goes through and updates any references to 'other area of need' to be 'related area of need'

### CODE REVIEW

**Comment by Thomas-Geraghty** [comment]
Apologies, looks like merging has ruined the history on this. All you need to do is review the content in this commit https://github.com/ministryofjustice/hmpps-sentence-plan-ui/pull/114/commits/773a5efcaade473d529d9d04f98fdfd880bc0f10

**Comment by pipwilson** [comment]
This looks good. Could we also get refactors of the `selectOtherAreasOfNeed` and `selectOtherAreasOfNeedRadio` used in `create-goal.cy.ts` please?

**Comment by Thomas-Geraghty** [comment]
>This looks good. Could we also get refactors of the selectOtherAreasOfNeed and selectOtherAreasOfNeedRadio used in create-goal.cy.ts please?

Addressed in https://github.com/ministryofjustice/hmpps-sentence-plan-ui/pull/114/commits/fd4f7983020cebc31a2951c6b06f13c47d8ca7a8

**Review by pipwilson — APPROVED** [review]
LGTM

**Pull request merged**
