### PR TITLE
SP2-270 - Minor fixes to create-steps

### PR DESCRIPTION
**Pull request by pk2453**

### CODE REVIEW

**Review by Thomas-Geraghty — DISMISSED** [review]
I think there's still a few issues with headings being too big. Also it looks like you've managed to set the 3 character popup enforcement on the autocomplete component, but I'm wondering how you've achieved this? I don't see it added on in the JS

**Comment by Thomas-Geraghty** [comment]
Pushed fixes now for my previous comment, https://github.com/ministryofjustice/hmpps-sentence-plan-ui/pull/56/commits/e9e907ffdbfe5b18d4fb14b4a6969c3568ed0cdd

**Comment by pk2453** [comment]
> I think there's still a few issues with headings being too big. Also it looks like you've managed to set the 3 character popup enforcement on the autocomplete component, but I'm wondering how you've achieved this? I don't see it added on in the JS

assets/js/accessible-autocomplete.min.js its updated here

**Review by pk2453 — COMMENTED** [review]
LGTM your changes @Thomas-Geraghty

**Comment by pipwilson** [comment]
> > I think there's still a few issues with headings being too big. Also it looks like you've managed to set the 3 character popup enforcement on the autocomplete component, but I'm wondering how you've achieved this? I don't see it added on in the JS
> 
> assets/js/accessible-autocomplete.min.js its updated here

I don't think we should be modifying this file - we should be using the minLength parameter (https://github.com/alphagov/accessible-autocomplete?tab=readme-ov-file#minlength-default-0) when creating the component in steps.js

**Review by pipwilson — APPROVED** [review]
I think there are still lots of problems with the overall output of this story and we'll need to open a new story (maybe in tech debt?) to fix both the problems here and update the design to the signed-off version, but hopefully along with the discussions with PO this should be good enough to get through our current review.

**Pull request merged**
